/**
 * Generates the secrets a self-hosted Supabase stack needs.
 *
 *   node scripts/generate-keys.mjs
 *
 * GoTrue signs user tokens with JWT_SECRET; PostgREST and storage-api verify
 * with the same secret. The anon and service keys are themselves JWTs signed
 * with it, carrying the Postgres role PostgREST should switch into.
 */
import { createHmac, randomBytes } from 'node:crypto'

const base64url = (input) =>
  Buffer.from(input).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')

function signJwt(payload, secret) {
  const header = base64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }))
  const body = base64url(JSON.stringify(payload))
  const signature = createHmac('sha256', secret)
    .update(`${header}.${body}`)
    .digest('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '')
  return `${header}.${body}.${signature}`
}

const jwtSecret = randomBytes(32).toString('hex')
const postgresPassword = randomBytes(24).toString('base64url')

const issuedAt = Math.floor(Date.now() / 1000)
// Ten years: these are infrastructure credentials, not user sessions.
const expiresAt = issuedAt + 60 * 60 * 24 * 365 * 10

const anonKey = signJwt({ role: 'anon', iss: 'supabase', iat: issuedAt, exp: expiresAt }, jwtSecret)
const serviceKey = signJwt(
  { role: 'service_role', iss: 'supabase', iat: issuedAt, exp: expiresAt },
  jwtSecret,
)

console.log(`# ---------------------------------------------------------------
# Generated by: node scripts/generate-keys.mjs
# Paste these into your .env. Keep SERVICE_ROLE_KEY server-side only.
# ---------------------------------------------------------------
POSTGRES_PASSWORD=${postgresPassword}
JWT_SECRET=${jwtSecret}
ANON_KEY=${anonKey}
SERVICE_ROLE_KEY=${serviceKey}
`)
